#TLS CONFIG YAML

  # Main config options for tls
  # Defaults for all options are nil values
tlsConfig :

  # Paths to Cert File & Key file from base directory
  # Both required for valid tls
  # Paths set as string values
  tlsCertPath : ""
  tlsKeyPath : ""

  # ServerName used to verify hostname on returned certs
  # unless Insecure Skip Verify is true
  serverName : ~ 

  # ClientAuth declares the policy the server will follow for client auth
  # Accepts the following string values and maps to ClientAuth Policies
  # NoClientCert                 
  # RequestClientCert            
  # RequireAnyClientCert         
  # VerifyClientCertIfGiven      
  # RequireAndVerifyClientCert   
  clientAuth : ~ 

  # ClientCa's accepts a string path to the set of CA's  
  clientCAs : ~

